#----------------------------
# Kubernetes manifests
#----------------------------
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}-deployment
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${IMAGE}
          ports:
            - containerPort: ${CONTAINER_PORT}
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: image-pull-secret
---
# Service
apiVersion: v1
kind: ClusterIP
metadata:
  name: ${APPLICATION_NAME}-service
  labels:
    app: ${APPLICATION_NAME}
spec:
  type: LoadBalancer
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - protocol: TCP
      port: ${EXPOSED_PORT}
      targetPort: ${CONTAINER_PORT}
